/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import static org.junit.Assert.*;

import java.util.Date;
import java.util.List;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
        System.out.println("test completed");
    }
    
    @Test
    public void testSelenium() throws Exception {
    	WebDriver driver = new ChromeDriver();
		try{
			driver.get("http://www.google.com/ncr");
			
			WebElement element = null;
			
			long start = new Date().getTime();
			long end = start;
			long timeout = 10000;
			while(element == null && end - start < timeout) {
				try {
					element = driver.findElement(By.cssSelector(".gsfi"));
				}
				catch(Exception e){
					Thread.sleep(100);
					end = new Date().getTime();
				}
				
			}
			
			if(element == null)
				throw new Exception("Element '.gsfi' not found");
			
			element.sendKeys("webdriver\n");
			
			List<WebElement> searchResults = null;
			
			start = new Date().getTime();
			end = start;
			while(searchResults == null && end - start < timeout) {
				try {
					searchResults = driver.findElements(By.cssSelector("div.g"));
				}
				catch(Exception e) {
					Thread.sleep(100);
					end = new Date().getTime();
				}
			}
			
			if(searchResults == null)
				throw new Exception("Search Results not found");
			else
				System.out.println(searchResults.size() + " Search Results found");
		}
		finally {
			driver.quit();
		}
	}
}
